"""Shared rendering helper for pull-request attachment content.

Produces a platform-agnostic Markdown document that both the GitHub and
GitLab pull-request steps can attach as a PR comment.
"""

# GitHub imposes a 65 536-char limit on issue/PR comments.
_MAX_BODY_CHARS = 60_000
_TRUNCATION_NOTICE = "\n\n… *(content truncated to fit platform limits)*"


def render_attachment_markdown(
    spec_text: str | None,
    plan_text: str | None,
    plan_summary: str | None,
) -> str | None:
    """Render a Markdown attachment for a pull-request comment.

    Returns ``None`` when both *spec_text* and *plan_text* are empty so the
    caller can skip posting altogether.

    Args:
        spec_text: The source issue description / specification.
        plan_text: The full implementation plan body.
        plan_summary: A short summary shown as the visible ``<details>``
            summary line for the plan section.

    Returns:
        A Markdown string ready to post, or ``None`` if there is nothing
        meaningful to render.
    """
    has_spec = bool(spec_text and spec_text.strip())
    has_plan = bool(plan_text and plan_text.strip())

    if not has_spec and not has_plan:
        return None

    parts: list[str] = ["## Rouge Review Context", ""]

    if has_spec:
        parts.extend(
            [
                "<details>",
                "<summary>Source Specification</summary>",
                "",
                spec_text.strip(),  # type: ignore[union-attr]
                "",
                "</details>",
                "",
            ]
        )

    if has_plan:
        summary_line = (
            f"**Summary:** {plan_summary.strip()}" if plan_summary and plan_summary.strip() else ""
        )
        parts.extend(
            [
                "<details>",
                "<summary>Implementation Plan</summary>",
                "",
            ]
        )
        if summary_line:
            parts.extend([summary_line, ""])
        parts.extend(
            [
                plan_text.strip(),  # type: ignore[union-attr]
                "",
                "</details>",
                "",
            ]
        )

    parts.extend(["---", "*Generated by Rouge*", ""])

    body = "\n".join(parts)

    if len(body) > _MAX_BODY_CHARS:
        body = body[:_MAX_BODY_CHARS] + _TRUNCATION_NOTICE

    return body
