"""Shared utility helpers for workflow step implementations."""

import json
import re
import subprocess
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    from rouge.core.workflow.step_base import WorkflowContext

from rouge.core.models import CommentPayload
from rouge.core.notifications.comments import emit_comment_from_payload
from rouge.core.utils import get_logger

# Max characters to log from LLM response
MAX_LOG_LENGTH = 500


def _sanitize_for_logging(text: Optional[str], max_length: int = MAX_LOG_LENGTH) -> str:
    """Sanitize text by redacting secrets and truncating to safe length.

    Redacts common secret patterns (API keys, tokens, emails) and truncates
    to max_length characters to prevent logging of sensitive/verbose content.

    Pattern matching is intentionally conservative to err on the side of safety.
    The final catch-all pattern may redact some non-sensitive data (e.g., hashes),
    but this trade-off is acceptable given the security risk of logging secrets.

    Args:
        text: Text to sanitize (None is converted to "[None]")
        max_length: Maximum length of returned string

    Returns:
        Sanitized and truncated text safe for logging
    """
    if text is None:
        return "[None]"

    # Redact common secret patterns
    sanitized = re.sub(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b", "[EMAIL]", text)
    # GitHub tokens: prefix + 36-40 chars (ghp_, gho_, ghu_, ghs_, ghr_)
    sanitized = re.sub(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}\b", "[GITHUB_TOKEN]", sanitized)
    # GitLab tokens: prefix + 20+ chars (glpat-, gldt-, gloas-, glcbt-)
    sanitized = re.sub(
        r"\b(?:glpat|gldt|gloas|glcbt)-[A-Za-z0-9_-]{20,}\b", "[GITLAB_TOKEN]", sanitized
    )
    # OpenAI-style API keys: sk- prefix
    sanitized = re.sub(r"\bsk-[A-Za-z0-9]{20,}\b", "[API_KEY]", sanitized)
    # Generic long alphanumeric tokens (catch-all for safety)
    sanitized = re.sub(r"\b[A-Za-z0-9]{32,}\b", "[TOKEN]", sanitized)

    # Truncate if longer than max_length
    if len(sanitized) > max_length:
        return sanitized[:max_length] + "..."
    return sanitized


# GitHub imposes a 65 536-char limit on issue/PR comments.
_MAX_BODY_CHARS = 60_000
_TRUNCATION_NOTICE = "\n\n… *(content truncated to fit platform limits)*"

_REVIEW_CONTEXT_MARKER = "<!-- rouge-review-context -->"


def render_attachment_markdown(
    spec_text: str | None,
    plan_text: str | None,
    plan_summary: str | None,
) -> str | None:
    """Render a Markdown attachment for a pull-request comment.

    Returns ``None`` when both *spec_text* and *plan_text* are empty so the
    caller can skip posting altogether.

    Args:
        spec_text: The source issue description / specification.
        plan_text: The full implementation plan body.
        plan_summary: A short summary shown as the visible ``<details>``
            summary line for the plan section.

    Returns:
        A Markdown string ready to post, or ``None`` if there is nothing
        meaningful to render.
    """
    has_spec = bool(spec_text and spec_text.strip())
    has_plan = bool(plan_text and plan_text.strip())

    if not has_spec and not has_plan:
        return None

    parts: list[str] = ["## Rouge Review Context", ""]

    if has_spec:
        parts.extend(
            [
                "<details>",
                "<summary>Source Specification</summary>",
                "",
                spec_text.strip(),  # type: ignore[union-attr]
                "",
                "</details>",
                "",
            ]
        )

    if has_plan:
        summary_line = (
            f"**Summary:** {plan_summary.strip()}" if plan_summary and plan_summary.strip() else ""
        )
        parts.extend(
            [
                "<details>",
                "<summary>Implementation Plan</summary>",
                "",
            ]
        )
        if summary_line:
            parts.extend([summary_line, ""])
        parts.extend(
            [
                plan_text.strip(),  # type: ignore[union-attr]
                "",
                "</details>",
                "",
            ]
        )

    parts.extend(["---", "*Generated by Rouge*", ""])

    body = "\n".join(parts)

    if len(body) > _MAX_BODY_CHARS:
        truncated = body[:_MAX_BODY_CHARS]
        unclosed = truncated.count("<details>") - truncated.count("</details>")
        if unclosed > 0:
            truncated += "\n" + "\n".join(["</details>"] * unclosed)
        body = truncated + _TRUNCATION_NOTICE

    return body


def load_and_render_attachment(context: "WorkflowContext") -> str | None:
    """Load fetch-issue and plan artifacts and render the PR/MR attachment markdown.

    Both GhPullRequestStep and GlabPullRequestStep use this to build the
    review-context comment body. Returns ``None`` when neither artifact is present.

    Args:
        context: The workflow context providing artifact loading.

    Returns:
        Rendered Markdown string, or ``None`` if both artifacts are absent.
    """
    from rouge.core.workflow.artifacts import FetchIssueArtifact, PlanArtifact

    issue_data = context.load_optional_artifact(
        "issue_data",
        "fetch-issue",
        FetchIssueArtifact,
        lambda a: {"description": a.issue.description},
    )
    plan_data = context.load_optional_artifact(
        "plan_data",
        "plan",
        PlanArtifact,
        lambda a: a.plan_data,
    )
    return render_attachment_markdown(
        spec_text=issue_data["description"] if issue_data else None,
        plan_text=plan_data.plan if plan_data else None,
        plan_summary=plan_data.summary if plan_data else None,
    )


def load_and_render_patch_attachment(context: "WorkflowContext") -> str | None:
    """Load fetch-patch and plan artifacts and render the PR/MR attachment markdown.

    This mirrors :func:`load_and_render_attachment` but reads from the
    ``fetch-patch`` artifact instead of ``fetch-issue``.  Returns ``None``
    when neither artifact is present.

    Args:
        context: The workflow context providing artifact loading.

    Returns:
        Rendered Markdown string, or ``None`` if both artifacts are absent.
    """
    from rouge.core.workflow.artifacts import FetchPatchArtifact, PlanArtifact

    patch_data = context.load_optional_artifact(
        "fetch_patch_data",
        "fetch-patch",
        FetchPatchArtifact,
        lambda a: {"description": a.patch.description},
    )
    plan_data = context.load_optional_artifact(
        "plan_data",
        "plan",
        PlanArtifact,
        lambda a: a.plan_data,
    )
    return render_attachment_markdown(
        spec_text=patch_data["description"] if patch_data else None,
        plan_text=plan_data.plan if plan_data else None,
        plan_summary=plan_data.summary if plan_data else None,
    )


def post_gh_attachment_comment(
    repo_path: str,
    pr_number: int,
    body: str,
    env: dict[str, str],
) -> None:
    """Post or update the Rouge review-context comment on a GitHub PR.

    Shared by GhPullRequestStep and ComposeCommitsStep so neither step
    module imports from a sibling step module.

    Args:
        repo_path: Path to the repository root.
        pr_number: The pull request number.
        body: Markdown body for the comment.
        env: Environment dict with the appropriate token set.
    """
    logger = get_logger(__name__)
    tagged_body = f"{_REVIEW_CONTEXT_MARKER}\n{body}"

    list_cmd = [
        "gh",
        "api",
        f"repos/{{owner}}/{{repo}}/issues/{pr_number}/comments?per_page=100",
    ]
    result = subprocess.run(
        list_cmd, capture_output=True, text=True, cwd=repo_path, env=env, timeout=30
    )

    existing_comment_id: int | None = None
    if result.returncode == 0 and result.stdout.strip():
        try:
            comments = json.loads(result.stdout)
            for comment in comments:
                if comment.get("body", "").startswith(_REVIEW_CONTEXT_MARKER):
                    existing_comment_id = int(comment["id"])
                    break
        except (ValueError, KeyError, TypeError, AttributeError):
            logger.debug("Failed to parse GitHub issue comments response for PR #%d", pr_number)
    elif result.returncode != 0:
        logger.warning(
            "Failed to list review-context comments on PR #%d in %s "
            "(phase=list-existing, exit_code=%d): %s",
            pr_number,
            repo_path,
            result.returncode,
            _sanitize_for_logging(result.stderr),
        )

    if existing_comment_id is not None:
        update_cmd = [
            "gh",
            "api",
            "--method",
            "PATCH",
            f"/repos/{{owner}}/{{repo}}/issues/comments/{existing_comment_id}",
            "-f",
            f"body={tagged_body}",
        ]
        update_result = subprocess.run(
            update_cmd, capture_output=True, text=True, cwd=repo_path, env=env, timeout=30
        )
        if update_result.returncode != 0:
            logger.warning(
                "Failed to update review-context comment on PR #%d in %s "
                "(phase=update, exit_code=%d): %s",
                pr_number,
                repo_path,
                update_result.returncode,
                _sanitize_for_logging(update_result.stderr),
            )
        else:
            logger.info("Updated review-context comment on PR #%d", pr_number)
    else:
        cmd = ["gh", "pr", "comment", str(pr_number), "--body", tagged_body]
        create_result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_path, env=env, timeout=30
        )
        if create_result.returncode != 0:
            logger.warning(
                "Failed to post review-context comment on PR #%d in %s "
                "(phase=create, exit_code=%d): %s",
                pr_number,
                repo_path,
                create_result.returncode,
                _sanitize_for_logging(create_result.stderr),
            )
        else:
            logger.info("Posted review-context comment on PR #%d", pr_number)


def post_glab_attachment_note(
    repo_path: str,
    mr_number: int,
    body: str,
    env: dict[str, str],
) -> None:
    """Post or update the Rouge review-context note on a GitLab MR.

    Shared by GlabPullRequestStep and ComposeCommitsStep so neither step
    module imports from a sibling step module.

    Args:
        repo_path: Path to the repository root.
        mr_number: The merge request IID.
        body: Markdown body for the note.
        env: Environment dict with the appropriate token set.
    """
    logger = get_logger(__name__)
    tagged_body = f"{_REVIEW_CONTEXT_MARKER}\n{body}"

    # NOTE: per_page=100 without pagination; duplicates possible on MRs with 100+ notes.
    list_cmd = [
        "glab",
        "api",
        f"projects/:id/merge_requests/{mr_number}/notes?per_page=100",
    ]
    result = subprocess.run(
        list_cmd, capture_output=True, text=True, cwd=repo_path, env=env, timeout=30
    )

    existing_note_id = None
    if result.returncode == 0 and result.stdout.strip():
        try:
            notes = json.loads(result.stdout)
            for note in notes:
                if note.get("body", "").startswith(_REVIEW_CONTEXT_MARKER):
                    existing_note_id = int(note["id"])
                    break
        except (ValueError, KeyError, TypeError, AttributeError):
            logger.debug("Failed to parse GitLab notes response for MR !%d", mr_number)

    if existing_note_id:
        update_cmd = [
            "glab",
            "api",
            "--method",
            "PUT",
            f"projects/:id/merge_requests/{mr_number}/notes/{existing_note_id}",
            "-f",
            f"body={tagged_body}",
        ]
        update_result = subprocess.run(
            update_cmd, capture_output=True, text=True, cwd=repo_path, env=env, timeout=30
        )
        if update_result.returncode != 0:
            logger.warning(
                "Failed to update review-context note on MR !%d: %s",
                mr_number,
                update_result.stderr,
            )
        else:
            logger.info("Updated review-context note on MR !%d", mr_number)
    else:
        cmd = ["glab", "mr", "note", str(mr_number), "--message", tagged_body]
        create_result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_path, env=env, timeout=30
        )
        if create_result.returncode != 0:
            logger.warning(
                "Failed to post review-context note on MR !%d: %s",
                mr_number,
                create_result.stderr,
            )
        else:
            logger.info("Posted review-context note on MR !%d", mr_number)


def _emit_and_log(issue_id: int, adw_id: str, text: str, raw: dict[str, Any]) -> None:
    """Helper to emit comment and log based on status.

    Args:
        issue_id: Issue ID
        adw_id: ADW ID
        text: Comment text
        raw: Raw payload data
    """
    logger = get_logger(adw_id)
    payload = CommentPayload(
        issue_id=issue_id,
        adw_id=adw_id,
        text=text,
        raw=raw,
        source="system",
        kind="workflow",
    )
    status, msg = emit_comment_from_payload(payload)
    if status == "success":
        logger.debug(msg)
    elif status == "skipped":
        logger.info(msg)
    else:
        logger.error(msg)
